@startuml
'https://plantuml.com/class-diagram

class App {
void main()
}

App <- websiteInfo

class websiteInfo {
String SiteName
String AuthorName
boolean JScriptFolder
boolean CSSFolder

websiteInfo promptInfo()
void generateWebsite()
}

@enduml