@startuml
'https://plantuml.com/class-diagram

class App {
void main()
String fileNamePrompt()
void writeToFile()
String replaceFile()
}

App <- word

class word {
{static} String targetWord

boolean isTarget()
void determineTarget()
String replaceWord()
}

@enduml